# tasks file for roles/web
- name: install httpd
  ansible.builtin.dnf:
    name: "{{ web_package }}"
    state: present

- name: Start httpd service
  ansible.builtin.service:
    name: "{{ web_service }}"
    state: started
    enabled: true

- name: Copy website data
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html
  notify:
    - Restart httpd
