---
- name: Check registered variable for emptiness
  hosts: centos
  tasks:
    - name: List contents of directory
      ansible.builtin.command: ls mydir
      register: contents
      changed_when: true
    - name: Check contents for emptiness
      ansible.builtin.debug:
        msg: "Directory is empty"
      when: contents.stdout == ""
