---
- name: First ansible playbook
  hosts: centos
  tasks:
    - name: Check if servers in "centos" group are available for ansible
      ansible.builtin.ping:
    - name: Reboot all servers in "centos" group
      ansible.builtin.reboot:
- name: Install packages
  hosts: centos
  vars_files:
    - vars/packages.yaml
  tasks:
    - name: Install java and git
      ansible.builtin.dnf:
        name: "{{ git_package }}"
        state: absent
